In [ ]:
import numpy as np

In [ ]:
def softmax(z, X):
  s = np.exp(z)/np.sum(np.exp(X))
  return s

In [ ]:
def sigmoid(z):
  sig = 1/(1+np.exp(-z))
  return sig

In [ ]:
#arr = np.array([[-0.5, 1.2, -0.1, 2.4]])
arr = np.random.randn(1,4)
arr, arr.mean()

(array([[ 2.02384511, -2.20854988,  0.86623596, -0.85088016]]),
 -0.04233724269802153)

In [ ]:
out_sm = np.zeros((arr.shape))
out_sig = np.zeros((arr.shape))

In [ ]:
for i in range(out_sm.shape[1]):
  out_sm[0,i] = softmax(arr[0,i], arr)
  out_sig[0,i] = sigmoid(arr[0,i])

In [ ]:
out_sm, out_sig

(array([[0.72192481, 0.0104806 , 0.22685518, 0.0407394 ]]),
 array([[0.88327802, 0.09898533, 0.70396188, 0.29924826]]))

In [ ]:
np.sum(out_sm), np.sum(out_sig)

(0.9999999999999999, 2.2370045452061604)